### ISSUE TITLE
[New Device] Parkside X20V Team 4Ah and 8Ah battery Lidl

### ISSUE THREAD

**Issue by Kosygor** [PlusPlus-ua/ha_tuya_ble#100]
Hello. 
Parkside X20V Team 4Ah battery Lidl
I am posting this data but I will try to manage to add it myself. 
After this I will aim to add also 8Ah batteries. 

To be clear:
4Ah I mean PAPS 204 A1
8Ah I mean PAPS 208 A1

1

```
"category": "dcb",
"product_id": "z5ztlw3k",
#"device_name": "Akumulator PARKSIDE Smart 4Ah 2",
"product_name": "PARKSIDE Smart battery 4Ah "
```
2

```
upper_temp_switch | Boolean | "{true,false}"
security_switch | Boolean | "{true,false}"
charge_current | Integer | {"unit": "mA","min": 0, "max": 30000, "scale": 0, "step": 100}
charge_voltage | Integer | {"unit": "mV","min": 0,"max": 25000,"scale": 1,"step": 100}
charge_times | Integer | {"unit": "次","min": 0, "max": 65535,"scale": 0,"step": 1}
discharge_times | Integer  | {"unit": "次","min": 0,"max": 65535,"scale": 0,"step": 1}
peak_current_times | Integer | {"unit": "次","min": 0,"max": 65535,"scale": 0,"step": 1}
temp_current | Integer | {"unit": "℃","min": -25,"max": 85,"scale": 0,"step": 1}
upper_temp_switch | Boolean | "{true,false}"
use_time | Integer | {"unit": "min","min": 0,"max": 65535,"scale": 0,"step": 1}
runtime_total | Integer	{"unit": "min","min": 0,"max": 16777215,"scale": 0,"step": 1}
battery_percentage | Integer | { "unit": "%","min": 0,"max": 100,"scale": 0,"step": 1}
security_switch	Boolean | "{true,false}"
```

3

`{"2":"Current charge current","3":"Charge voltage","8":"Number of loading cycles","9":"Number of discharge cycles","10":"Overcurrent counter","11":"Temperature","12":"Overheated alarm switch","14":"Use time","15":"Total runtime","16":"Battery power","18":"Device info","19":"Product type","21":"Fault","22":"Security switch","101":"电池包放电电流","102":"电池包充放电状态","103":"预计充电完成倒计时","104":"预计电池包续航时间 ","105":"Battery work mode","106":"电池片防盗PIN码","107":"电压过高次数 ","108":"电压过低次数 ","109":"放电中温度过高次数","110":"充电中温度过高次数","111":"放电中温度过低次数","112":"充电中温度过低次数","113":"短路次数","114":"过流次数","115":"电池包指示灯闪","116":"电池包低电压保护值","117":"电池包恒流放电电流值","150":"工具型号//制造批次","151":"工具PID/固件版本/工具名称","152":"Tool rotation speed","153":"Tool torque","154":"Tool total runtime","155":"Took kick back","156":"Tool fault error tip","157":"Tool discharge current","158":"Tool over temperature times","159":"Tool locked times","160":"Tool overcurrent times","161":"Tool work mode","162":"Reset to factory","163":"lamp switch","164":"Tool light brightness","165":"Tool light delay off setting","166":"工具扭矩可调最大值","167":"工具速度可调最大值","168":"工具电流可调最大值","169":"工具所用到的DPID","170":"CW/CCW Control","171":"Tool CW/CCW","172":"Battery current temp","173":"Tool kick back adjust","174":"下发电池包工作模式","175":"档位范围","176":"Current Level","177":"Tools work mode","178":"Tool relative speed adjustment","179":"Tool discharge current","180":"小功率工具放电电流最大值","181":"Air pump pressure","182":"气泵压强最大值","183":"Schedule shutdown","184":"定时器最大值","185":"Laser On/Off","186":"Pulse Mode On/Off","187":"激光线控制范围","188":"Laser Line Control","189":"激光功率范围","190":"Laser Power Control","191":"复合功能点1描述","192":"复合功能点1","193":"复合功能2描述","194":"复合功能点2","195":"复合功能点3描述","196":"复合功能点3","197":"复合功能点4描述","198":"复合功能点4"}
`
4

```
2024-01-05 11:27:53.059 ERROR (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4E:AE:A5:CF: timeout receiving response, RSSI: -57
2024-01-05 11:27:53.059 ERROR (MainThread) [custom_components.tuya_ble.tuya_ble.tuya_ble] DC:23:4E:AE:A5:CF: Sending device info request failed
```

Edit: OK these 4Ah  will not play nice with ESPhome Bluetooth Proxy.  they are disconnecting all the time and will not send any packets.
8Ah (at least 3 out of 4 that I have) are readable by Integration.
for now I have added simplest parameters, so this is lacking switches and sensor that are integer ...

Add to sensor.py
```
    "dcb": TuyaBLECategorySensorMapping(
        products={
            **dict.fromkeys(
                ["ajrhf1aj"], # PARKSIDE Smart battery 8Ah
                [
                    TuyaBLEBatteryMapping(dp_id=16),
                    TuyaBLETemperatureMapping(dp_id=11),
                    TuyaBLESensorMapping(
                        dp_id=2,
                        description=SensorEntityDescription(
                            key="charge_current",
                            device_class=SensorDeviceClass.CURRENT,
                            native_unit_of_measurement=UnitOfElectricCurrent.MILLIAMPERE,
                            state_class=SensorStateClass.MEASUREMENT,
                        ),
                    ),
                    TuyaBLESensorMapping(
                        dp_id=3,
                        description=SensorEntityDescription(
                            key="charge_voltage",
                            device_class=SensorDeviceClass.VOLTAGE,
                            native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
                            state_class=SensorStateClass.MEASUREMENT,
                        ),
                    ),
                    TuyaBLESensorMapping(
                        dp_id=14,
                        description=SensorEntityDescription(
                            key="use_time",
                            device_class=SensorDeviceClass.DURATION,
                            native_unit_of_measurement=UnitOfTime.MINUTES,
                            state_class=SensorStateClass.MEASUREMENT,
                        ),
                    ),
                    TuyaBLESensorMapping(
                        dp_id=15,
                        description=SensorEntityDescription(
                            key="runtime_total",
                            device_class=SensorDeviceClass.DURATION,
                            native_unit_of_measurement=UnitOfTime.MINUTES,
                            state_class=SensorStateClass.MEASUREMENT,
                        ),
                    ),
                ],
            ),
        }
    ),
```
Add to devices.py:
```
    "dcb": TuyaBLECategoryInfo(
        products={
            **dict.fromkeys(
                [
                    "ajrhf1aj",
                ],
                    TuyaBLEProductInfo(  # device product_id
                    name="PARKSIDE Smart battery 8Ah",
                ),
            ),
        },
    ),
```

Be advised that I am putting this as beta.
I do not know if the BT proxy talking to the batteries will have any impact on their idle drainage. 

I am adding Excel sheet with data collected from HA Log and Tuya IoT platform.
[Parkside.xlsx](https://github.com/PlusPlus-ua/ha_tuya_ble/files/13844116/Parkside.xlsx)

Note: I was approaching 4Ah with HCI log and Wireshark but there is no standard communication.

**Comment by Kosygor** [comment]
This is kind of OT but I will make separate comment about this. 
Maybe it is oblivious but, just wow. If you will keep not fully supported entities (in my case 4Ah bat) CPU Load will go trough roof. It is not happening right away so it is not that noticeable.
![obraz](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/61921662/4f5750c1-0c56-45d4-b00e-7c53bb734700)

**Comment by Kosygor** [comment]
![obraz](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/61921662/9b3d1ca5-535f-41b8-9013-26768ed66ff8)
If You are going to use my setup please consider significant power drain.

Edit: 
If You are also using ESPhome BT proxy. Temp fix for that that I have just briefly tested is:
Add ESPhome configuration that will create service to HA that will enable You to start/stopscans so You could limit drain:
```
api:
  encryption:
     key: #placeyours
  services:
    - service: btstartscan
      then:
        - esp32_ble_tracker.start_scan
    - service: btstopscan
      then:
        - esp32_ble_tracker.stop_scan

esp32_ble_tracker:
  scan_parameters:
    active: true # 
    continuous: False 
````

Find line in custom_compontnets/tuya_ble/__init__.py and overvrite `...Mode.ACTIVE` with ...Mode.PASSIVE`
```
    entry.async_on_unload(
        bluetooth.async_register_callback(
            hass,
            _async_update_ble,
            BluetoothCallbackMatcher({ADDRESS: address}),
            bluetooth.BluetoothScanningMode.PASSIVE, # changed from ACTIVE changed 1906 09012024
        )
    )
```
Approx battery drain without constant connection is 0,3 % per day , compered to 2,5% per day ... 

There is still problem with batteries connection so it is up to 3 batteries that are able to being connected at the same time. 
I have to figure out how to deal with this. Best solution would be to limit connection time per day.

**Comment by titou4307** [comment]
Hi
I have try to add my two battery Parkside but not I have this error logs : 

```
Invalid Config
The following integrations and platforms could not be set up:

    tuya_ble.sensor ([Show logs](http://192.168.1.30:8123/config/logs?filter=tuya_ble.sensor))

Please check your config and [logs](http://192.168.1.30:8123/config/logs).
```

Logs : 

```
Home Assistant Core
Unable to prepare setup for platform 'tuya_ble.sensor': Platform not found (Exception importing custom_components.tuya_ble.sensor).
13:34:25 – (ERREUR) setup.py - message survenu pour la première fois à 13:34:10 et apparu 2 fois.
Unexpected exception importing platform custom_components.tuya_ble.sensor
13:34:25 – (ERREUR) loader.py - message survenu pour la première fois à 13:34:10 et apparu 2 fois.
```
Error 1 setup.py : 

```
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 13:34:10 (2 occurrences)
Last logged: 13:34:25

Unable to prepare setup for platform 'tuya_ble.sensor': Platform not found (Exception importing custom_components.tuya_ble.sensor).
```

Error 2 loader.py : 

```
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 13:34:10 (2 occurrences)
Last logged: 13:34:25

Unexpected exception importing platform custom_components.tuya_ble.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tuya_ble/sensor.py", line 321, in <module>
    native_unit_of_measurement=UnitOfElectricCurrent.MILLIAMPERE,
                               ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'UnitOfElectricCurrent' is not defined
```
Does anyone has a little first reponse ?

**Comment by titou4307** [comment]
Here the errors : 

![BLE Tuya 4](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/56826797/ef914f5b-7b11-4fdc-8c79-bf0c8d51f796)

![BLE Tuya 5](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/56826797/fee7b8bb-2c90-4795-bbac-1bccacf8f858)

![BLE Tuya 6](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/56826797/b881fdc2-7e69-4f95-b103-cdfcb3a18440)

**Comment by titou4307** [comment]
Heelo at all

I think I have solved this error : 

![BLE Tuya 6](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/56826797/b881fdc2-7e69-4f95-b103-cdfcb3a18440)

Add to sensor.py (in complement of @Kosygor before...) after line 23 for me...

```
    UnitOfElectricCurrent,
    UnitOfElectricPotential
```

After this and restart my two battery appears with 7 entity each.....

But can read values ...
Here the error new error : 

```
Logger: custom_components.tuya_ble.tuya_ble.tuya_ble
Source: custom_components/tuya_ble/tuya_ble/tuya_ble.py:627
Integration: Tuya BLE
First occurred: 23:29:13 (2 occurrences)
Last logged: 23:29:32

DC:23:4D:BE:6A:A0: Sending device info request failed
DC:23:4D:BE:B9:9C: Sending device info request failed
```
![BLE Tuya 7](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/56826797/7abc020e-b3ea-461f-aeae-12045c17d364)

![BLE Tuya 8](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/56826797/21419bcb-f47d-41c4-871a-e6218b083bf7)

**Comment by Kosygor** [comment]
@titou4307 You are right about `UnitOfElectricCurrent and UnitOfElectricPotential` I have forgot that during playing around with this integration I have upgraded few lines of code. 

It will be more like guessing but:
What kind of BT adapter are you using ? 
Maybe some logs from device itself would help. 
Can You see these devices in your project on Tuya IoT platform ?
If so are You sure that no other devices are connected to batteries (ex. smartphone?).

**Comment by titou4307** [comment]
Hello

here the copy screen of my Tuya Iot platform : 

![Tuya 20](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/56826797/ebe70b7f-9b68-43fa-8b5d-ee8d5a3fcca7)

The battery appears not connected

I use EST-POE-32 with the firmware Bluetooth Proxy you give link to me
I will look at logs if it exist....

None smartphone are connected with App Lidl or App Tuya. I have verify and the two Apps are disconnected....

But I have integration local tuya in Home Assistant with the charger and it use the same user/pswd ???

Other; I have not done your edit here : 

Edit:
If You are also using ESPhome BT proxy. Temp fix for that that I have just briefly tested is:
Add ESPhome configuration that will create service to HA that will enable You to start/stopscans so You could limit drain:

```
api:
  encryption:
     key: #placeyours
  services:
    - service: btstartscan
      then:
        - esp32_ble_tracker.start_scan
    - service: btstopscan
      then:
        - esp32_ble_tracker.stop_scan

esp32_ble_tracker:
  scan_parameters:
    active: true # 
    continuous: False 

Find line in custom_compontnets/tuya_ble/init.py and overvrite ...Mode.ACTIVE with ...Mode.PASSIVE`

    entry.async_on_unload(
        bluetooth.async_register_callback(
            hass,
            _async_update_ble,
            BluetoothCallbackMatcher({ADDRESS: address}),
            bluetooth.BluetoothScanningMode.PASSIVE, # changed from ACTIVE changed 1906 09012024
        )
    )

```
Approx battery drain without constant connection is 0,3 % per day , compered to 2,5% per day ...

There is still problem with batteries connection so it is up to 3 batteries that are able to being connected at the same time.
I have to figure out how to deal with this. Best solution would be to limit connection time per day.

Other question : Does it needeed to type Device ID of battery into the file sensor.py ??

**Comment by titou4307** [comment]
Here my YAML from bluetooth proxy (I have replace the api Key and the OTA password ..... for security ; ) )

```
substitutions:
  name: esp32-bluetooth-proxy-705314
  friendly_name: Bluetooth Proxy 705314
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
# Enable Home Assistant API
api:
  encryption:
    key: "key"

ota:
  password: "password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

And here the log from esphome integration of the ESP32 (I have replace MAC Address, SSID and other ......from security too)

```
INFO ESPHome 2023.12.6
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-705314.yaml...
INFO Starting log output from 192.168.1.25 using esphome API
INFO Successfully connected to esp32-bluetooth-proxy-705314 @ 192.168.1.25 in 0.046s
INFO Successful handshake with esp32-bluetooth-proxy-705314 @ 192.168.1.25 in 0.128s
[12:17:35][I][app:102]: ESPHome version 2023.12.6 compiled on Jan 15 2024, 22:45:28
[12:17:35][I][app:104]: Project esphome.bluetooth-proxy version 1.0
[12:17:35][C][wifi:573]: WiFi:
[12:17:35][C][wifi:405]:   Local MAC: 00:00:00:00:00:00
[12:17:35][C][wifi:410]:   SSID: 'Livebox-0000'[redacted]
[12:17:35][C][wifi:411]:   IP Address: 192.168.1.25
[12:17:35][C][wifi:413]:   BSSID: 00:00:00:00:00:00[redacted]
[12:17:35][C][wifi:414]:   Hostname: 'esp32-bluetooth-proxy-705314'
[12:17:35][C][wifi:416]:   Signal strength: -56 dB ▂▄▆█
[12:17:35][C][wifi:420]:   Channel: 1
[12:17:35][C][wifi:421]:   Subnet: 255.255.255.0
[12:17:35][C][wifi:422]:   Gateway: 192.168.1.1
[12:17:35][C][wifi:423]:   DNS1: 192.168.1.1
[12:17:35][C][wifi:424]:   DNS2: 0.0.0.0
[12:17:35][C][logger:439]: Logger:
[12:17:35][C][logger:440]:   Level: DEBUG
[12:17:35][C][logger:441]:   Log Baud Rate: 115200
[12:17:35][C][logger:443]:   Hardware UART: UART0
[12:17:35][C][bluetooth_proxy:088]: Bluetooth Proxy:
[12:17:35][C][bluetooth_proxy:089]:   Active: YES
[12:17:35][C][safe_mode.button:022]: Safe Mode Button 'Safe Mode Boot'
[12:17:35][C][safe_mode.button:022]:   Icon: 'mdi:restart-alert'
[12:17:35][C][esp32_ble:374]: ESP32 BLE:
[12:17:35][C][esp32_ble:376]:   MAC address: 00:00:00:00:00:00
[12:17:35][C][esp32_ble:377]:   IO Capability: none
[12:17:35][C][esp32_ble_tracker:645]: BLE Tracker:
[12:17:35][C][esp32_ble_tracker:646]:   Scan Duration: 300 s
[12:17:35][C][esp32_ble_tracker:647]:   Scan Interval: 320.0 ms
[12:17:35][C][esp32_ble_tracker:648]:   Scan Window: 30.0 ms
[12:17:35][C][esp32_ble_tracker:649]:   Scan Type: ACTIVE
[12:17:35][C][esp32_ble_tracker:650]:   Continuous Scanning: True
[12:17:35][C][mdns:115]: mDNS:
[12:17:35][C][mdns:116]:   Hostname: esp32-bluetooth-proxy-705314
[12:17:35][C][ota:097]: Over-The-Air Updates:
[12:17:35][C][ota:098]:   Address: esp32-bluetooth-proxy-705314.local:3232
[12:17:35][C][ota:101]:   Using Password.
[12:17:35][C][api:139]: API Server:
[12:17:35][C][api:140]:   Address: esp32-bluetooth-proxy-705314.local:6053
[12:17:35][C][api:142]:   Using noise encryption: YES
[12:17:35][C][improv_serial:032]: Improv Serial:
```

I think the ESP32 Bluetooth proxy is OK because at the first time of the starting Tuya BLE only one battery was found because it was near the proxy
The second battery was not foung because not near (more than 10meters......3 walls....)
I have put this second battery near the Bluetooth proxy and instantly it was found...

**Comment by Kosygor** [comment]
Ok it looks good with IoT platform. They will not be online since whole point of Tuya BLE integration is to get data locally. 
Another question: I How is charger connected ? BLE/WiFI ? 
I can send You my files if you want to.

**Comment by titou4307** [comment]
Hi

The charger is connected by wifi to the integration local tuya.....

Does it needeed to change like your edit for the time connection ?

Does it needeed to type Device ID of my two battery into the file sensor.py ?? ID in the IoT platform ?
["ajrhf1aj"] by ID of my battery ??

Yes if possible I would like your files .....Thanks !!

**Comment by Kosygor** [comment]
> Yes if possible I would like your files .....Thanks !!
Here You go. [devices&sensors.zip](https://github.com/PlusPlus-ua/ha_tuya_ble/files/13966513/devices.sensors.zip)

> Does it needeed to change like your edit for the time connection ?
 I do not understand. If You meant if changes from [this](https://github.com/PlusPlus-ua/ha_tuya_ble/issues/100#issuecomment-1881843598) post are necessary.  No they are not. They are shortcut ( i am convinced that there is better way to do this but I do not know how) to save power. But everything was working before that. 

> Does it needed to type Device ID of my two battery into the file sensor.py ?? ID in the IoT platform ? ["ajrhf1aj"] by ID of my battery ??
Well i am not sure if iI get his but: as You can see in my files "ajrhf1aj" was added in 
devices.py for integration to recognize device itself (and I think that You have done it right, since batteries were discovered) 
sensors.py for integration to know what sensors these value should represent. - and probably You also have it right, because they were created but are not refreshed... 
I am now prone to guess that something maybe different with your batteries or BT side.

**Comment by titou4307** [comment]
Hello @Kosygor 

sorry for my late response....
It seems all was OK, After my last message I have a notification for an update of Home Assistant (Home assistant Core .. of memory)

After restart Home Assistant (restart the matérial.....) all the sensors/switch appears properly

My bluetooth proxy is POE i will try to power this with RJ45 cable and see if the connection with battery stay..

Claude (from France)

One more time : many many thanks

**Comment by titou4307** [comment]
Hello

I have a new battery BT 4Ah who is detected as an 8Ah...
Does it possible to identify properly this battery

@Kosygor : I have read you have try ?

**Comment by cibernox** [comment]
I've been trying the same thing, one year later. I'm making progress adding more and more entities. A big one is that I was able to mimic the funcionality where you can make the LED of a battery flash to distinguish one battery from the others.

![Image](https://github.com/user-attachments/assets/0688fad8-4a12-4038-b14e-185802e1feeb)

So far the main problem is that I found the connection to be somewhat unreliable, but my bluetooth is in my server a couple rooms away from my garage and connection is indeed very week. I need to try adding bluetooth proxies to see if that helps at all.

**Comment by cibernox** [comment]
I'm facing one problem @titou4307 that maybe you faced too.
The integration (not this one but one fork that does work with the latest home assistant) detects all my batteries but for some reason I only seems to be able to actually read and write to one. The others are detected but all their entities stay unavailable forever.

**Comment by milandzuris** [comment]
> I'm facing one problem [@titou4307](https://github.com/titou4307) that maybe you faced too. The integration (not this one but one fork that does work with the latest home assistant) detects all my batteries but for some reason I only seems to be able to actually read and write to one. The others are detected but all their entities stay unavailable forever.

Hi, which integration is this? Could you send me the URL? Thanks.
