### ISSUE TITLE
Error Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Ben00793** [PlusPlus-ua/ha_tuya_ble#123]
Hello,
Does anyone seen this issue before? when i'm trying to add the integration to HA I get this message:
Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

This is the log file:

Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 00:37:38 (2 occurrences)
Last logged: 00:41:30

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 71, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1155, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1175, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1312, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2608, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2585, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 551, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 53, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 176, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 193, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 275, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 303, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for tuya_ble not found: ['pycountry==22.3.5'].

**Comment by cocolino83** [comment]
I have the same problem too.  I don't know how to make tuya BLE work.  thanks for help.

![Screenshot_20240414-200347](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/88486650/e5cd18a7-7fd7-49d7-9d35-80521b307a4c)

**Comment by Diaryofamadman** [comment]
Same problem here.

**Comment by OsaedYahya** [comment]
Same issue here

**Comment by OsulivanAB** [comment]
Same

**Comment by markusg1234** [comment]
Which branch are you using? The original is not in working condition.
You could try some of these branches.
https://github.com/PlusPlus-ua/ha_tuya_ble/forks?include=active&page=1&period=2y&sort_by=last_updated

**Comment by OsulivanAB** [comment]
> Which branch are you using? The original is not in working condition. You could try some of these branches. https://github.com/PlusPlus-ua/ha_tuya_ble/forks?include=active&page=1&period=2y&sort_by=last_updated

Thank you, in and working off of your branch

**Comment by cocolino83** [comment]
> Quale ramo stai usando? L'originale non è funzionante. Potresti provare alcuni di questi rami. https://github.com/PlusPlus-ua/ha_tuya_ble/forks?include=active&page=1&period=2y&sort_by=last_updated

first of all thank you for your help.
I tried different branches. some of them allow me to enter the credentials, but unfortunately even if I have two Bluetooth devices on Tuya "No unconfigured devices found" I can't understand why. they are not connected to any hub they are simply registered on the tuya app. on tuya of home assistant they are mentioned. I don't know if this can be a problem but I noticed that I don't have the tuya folder in custom components. I tried to uninstall and install tuya but the folder is not created. now I ask if there is a way to understand what the problem is that I cannot integrate these bluetooth devices. I hope for help thanks

![Screenshot 2024-04-24 210257](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/88486650/d71e6cae-56dd-4f29-a865-349adb025db2)
![Screenshot 2024-04-24 210326](https://github.com/PlusPlus-ua/ha_tuya_ble/assets/88486650/ec5ce8fe-9646-4e30-8091-b92dcb6d6b45)

**Comment by edricksuarez** [comment]
I got this same issue with No unconfigured devices found any idea how to resolve this?

**Comment by markusg1234** [comment]
> > Quale ramo stai usando? L'originale non è funzionante. Potresti provare alcuni di questi rami. https://github.com/PlusPlus-ua/ha_tuya_ble/forks?include=active&page=1&period=2y&sort_by=last_updated
> 
> first of all thank you for your help. I tried different branches. some of them allow me to enter the credentials, but unfortunately even if I have two Bluetooth devices on Tuya "No unconfigured devices found" I can't understand why. they are not connected to any hub they are simply registered on the tuya app. on tuya of home assistant they are mentioned. I don't know if this can be a problem but I noticed that I don't have the tuya folder in custom components. I tried to uninstall and install tuya but the folder is not created. now I ask if there is a way to understand what the problem is that I cannot integrate these bluetooth devices. I hope for help thanks
> 

Not all devices are supported and this maybe the issue.

It could be the Temperature and Humidity Sensor has a different category_id to the wsdcg that does work.
Also I don't think lights are supported unless someone has added them to a fork.
I only have a soil moisture sensor and a finger bot.

You may already know, that you need a Bluetooth dongle with the HA Bluetooth integration as well as the tuya BLE integration. ESPHome Bluetooth proxy should also work instead of the Bluetooth integration, but I haven't tried it.

Regards,
Markus

**Comment by Arty2k15** [comment]
Same problem here, also with error message resulting in
`homeassistant.requirements.RequirementsNotFound: Requirements for tuya_ble not found: ['pycountry==22.3.5'].`

No idea how to solve.

I guess the problem is the following error:
`Unable to install package pycountry==22.3.5: ERROR: Cannot install pycountry==22.3.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible`
HA is running on Proxmox 8.1.3.

**Comment by Wummeke** [comment]
Same issue here.
I installed the integration through HACS, and straight after the reboot, adding the integration fails with the same error as mentioned earlier.

Edit: this fork works: https://github.com/markusg1234/ha_tuya_ble
