### ISSUE TITLE
Login error (2401): username or password wrong

### ISSUE THREAD

**Issue by andypnz** [PlusPlus-ua/ha_tuya_ble#4]
Hi. I get the above error despite using my correct Tuya IOT username / password.

I already have all the required fingerbot info (UUID, local key, MAC address, etc).

Is it possible to enter this configuration information manually somewhere?

Thanks!
Andrew

**Comment by PlusPlus-ua** [comment]
Hi, have you selected the right country from the list? Datacenter to login, depends on selected country and wrong datacenter doesn't know your credentials.

**Comment by andypnz** [comment]
Yes… New Zealand selected - which should use the Western America data Center…

**Comment by andypnz** [comment]
I don’t have a hub - I think the official integration requires a hub, right?

**Comment by PlusPlus-ua** [comment]
> I don’t have a hub - I think the official integration requires a hub, right?

No, it requires the hub only for Bluetooth or ZigBee devices, WiFi devices could communicate with cloud directly. This integration uses the same tuya_iot python package as the official integration to obtain device credentials during setup.

**Comment by andypnz** [comment]
Ok, I will install that and try signing in when I get home later today - and reply back…

thanks for your help :-)

**Comment by andypnz** [comment]
Ok, so it needed my password for the smart life app (not the Tuya IOT platform).... so fist device configured and working no problem :-)

Second identical device I get this error:

`Logger: homeassistant.config_entries
Source: components/bluetooth/wrappers.py:269
First occurred: 1:20:06 PM (1 occurrences)
Last logged: 1:20:06 PM

Error setting up entry Fingerbot Plus xxxxxx for tuya_ble
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_ble/__init__.py", line 44, in async_setup_entry
    await device.initialize()
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 272, in initialize
    await self.update()
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 312, in update
    await self._send_packet(TuyaBLECode.FUN_SENDER_DEVICE_STATUS, bytes())
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 834, in _send_packet
    await self._ensure_connected()
  File "/config/custom_components/tuya_ble/tuya_ble/tuya_ble.py", line 584, in _ensure_connected
    client = await establish_connection(
  File "/usr/local/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 344, in establish_connection
    await client.connect(
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 269, in connect
    connected = await super().connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 204, in connect
    reply = await self._bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 371, in call
    await future
asyncio.exceptions.CancelledError
`

Any ideas?

**Comment by PlusPlus-ua** [comment]
Then I close the issue.

**Comment by StaRipper** [comment]
This Solve It:
https://community.home-assistant.io/t/tuya-integration-error-2406-skill-id-invalid/372831/16
