### ISSUE TITLE
Still having problems with "500 internal server error"

### ISSUE THREAD

**Issue by aportillo365** [PlusPlus-ua/ha_tuya_ble#8]
Thanks a lot for your contribution

Unfortunately I cannot add the integration (release 0.1.2), please have a look on the logs, any hint its welcome!

Logger: aiohttp.server
Source: custom_components/tuya_ble/config_flow.py:114
Integration: Tuya BLE
First occurred: 00:10:17 (5 occurrences)
Last logged: 14:27:19

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 234, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 831, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 859, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_ble/config_flow.py", line 243, in async_step_user
    return await self.async_step_login()
  File "/config/custom_components/tuya_ble/config_flow.py", line 277, in async_step_login
    return _show_login_form(self, user_input, errors, placeholders)
  File "/config/custom_components/tuya_ble/config_flow.py", line 114, in _show_login_form
    def_country = pycountry.countries.get(alpha_2=flow.hass.config.country)
  File "/usr/local/lib/python3.10/site-packages/pycountry/db.py", line 39, in load_if_needed
    return f(self, *args, **kw)
  File "/usr/local/lib/python3.10/site-packages/pycountry/db.py", line 111, in get
    raise LookupError()
LookupError

**Comment by PlusPlus-ua** [comment]
Please try version 0.1.3 - it should be fixed there

**Comment by aportillo365** [comment]
Thank you sou much!! Version 0.1.3 was able to show the credentials configuration wizard and after that, the devices can be discovered both with Raspberry PI BLE adapter or ESP32 Bluetooth proxy active.

Once the devices were integrated, in the beginning I was not able to control them. Just the battery entities inform about the charging status and baterry level

I realized that it was necessary to "set" the mode of the Cubetouch II, as follows:

![1](https://user-images.githubusercontent.com/75343249/235295447-67bcd222-4c62-4a48-8313-e218b173ecc8.png)
![2](https://user-images.githubusercontent.com/75343249/235295503-74d6c155-aba9-4169-9cd7-4bf89a61a2d8.png)

After the mode is selected (Push/ Switch), the above controls are available:

![3](https://user-images.githubusercontent.com/75343249/235295522-936241c6-7721-4773-ab93-0ac312855221.png)



Thanks a lot again

**Comment by Cres09** [comment]
I can now too go through the wizard, and it founds the fingerbot, but when I add it, no entities are shown besides signal strength.
![Captura](https://user-images.githubusercontent.com/118302081/235346093-b47a1e89-76f0-42fc-88d5-19ab73729000.PNG)

**Comment by PlusPlus-ua** [comment]
> I can now too go through the wizard, and it founds the fingerbot, but when I add it, no entities are shown besides signal strength.

This means that your device has product_id, which is not included in integration for now. In order to add product_id I need this id itself (this is the text in parentheses after the word Fingerbot on your screenshot).

Next, I need to understand which kind of Fingerbot it is.

A better way is to obtain ids of all datapoints for your device. Here is described how to do it:
https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_9-find-your-data-point

**Comment by PlusPlus-ua** [comment]
> I can now too go through the wizard, and it founds the fingerbot, but when I add it, no entities are shown besides signal strength.

I'm going to close this issue, please open a new issue for support of your device.
